### ISSUE TITLE
Usar base de datos MS Access en un a tablet

### ISSUE THREAD

**Issue by ARMasso** [ACCESSoTOTAL/Dudas#10]
Tengo creada una base de datos con sus formularios para recoger medidas de obra de edificación.
Me gustaría llevar esa aplicación a una tablet para que se puedan tomar medidas in situ en la misma obra.

¿hay alguna forma de usar esa base de datos en una tablet que no sea a través de Power Apps?

**Comment by lunasoft2001** [comment]
Lo más cómodo es usar escritorios remotos a través de html5.
Yo utilizo TS Plus, que es bastante económico y de pago único.
Así puedes conectar desde la tablet, movil, ... a un escritorio remoto, e incluso a una única aplicación (en mi caso una app de access adaptada a la resolución del dispositivo a usar).

Otros modos son:

crear una app con Blazor (o similar) que permite conectarse al sql server en el que estén los datos (si tienes sql server)

Usar Trello como plataforma puente y con los campos personalizables (de pago) introducir los datos y luego recogerlos desde Access leyendo la RESP API de Trello.
