### ISSUE TITLE
Sería viable "apostar" por ACCESS ???

### ISSUE THREAD

**Issue by JavierPriv** [ACCESSoTOTAL/Dudas#12]
**Descripción del problema:**
Buenos días, como es mi primer contacto en el foro no sé si estoy poniendo mi consulta en el lugar adecuado...

Tenemos la necesidad para un cliente de gestionar el inventario de su almacén (solo por poner en antecedentes).
La cuestión y nuestra duda viene por la necesidad de no únicamente gestionar "campos de información" sino la necesidad y requerimiento de incluir imágenes de todos y cada uno de los productos en su maestro de productos.

Nos hemos planteado ir a una solución medida con Access por la gran cantidad de campos particulares de información que gestionan en su maestro de materiales vs. optar por una aplicación estándar dentro de un ERP o integrada con él pero en la que deberíamos de ampliar esos campos en el estándar.

Nuestra duda principal viene de la  limitación de que el tamaño de la BBDD es de hasta 2Gb (creo que actualmente ya son hasta 5Gb aunque sino podríamos ir con otras BBDD MySQL, MariaDB, MS SQLServer...) y nuestro temor a que por "el peso de las imágenes" (aunque definamos el campo "Fotos" como DATOS ADJUNTOS residentes en otras carpetas de imágenes) nos limite o tengamos problemas de rendimiento y nos obligue a ir a una solución "estándar" en la nube
PD: incluso del tipo de Shopify porque aunque no es un ERP como sabéis pero los eCommerce al final gestionan almacenes de stock y maestros de productos con muchas muchas imágenes por supuesto.

Esta es la duda porque aunque hemos estado buscando info y "aparentemente" por lo que hemos visto no debería de ser un problema pero lo queríamos contrastar en el Foro o si tenéis recomendación al respecto de como gestionar imágenes asociadas a los productos en este caso.

Gracias de antemano.
Un saludo,
Javier Herranz

**Código:**
```
Escribe aquí el código (si procede)
```

**Captura de pantalla:**
Aquí puedes colocar las capturas de pantalla que ayuden a entender el problema

**Archivos:**
Si lo deseas, puedes subir tu archivo

**Comment by lunasoft2001** [comment]
Hola Javier:
publicaste la pregunta en el lugar adecuado. Muchas gracias.

MI consejo es que NO guardes las imágenes en la bas de datos. En la base de datos guardaría la ruta en la que se encuentra la imagen. De este modo reduces el tamaño de la base de datos y facilitas la interacción con las imágenes desde otros medios. Si quieres que hablemos del tema más profundamente no dudes en contactar conmigo a través de juanjo@luna-soft.es

Un saludo

**Comment by JavierPriv** [comment]
Tomo nota al respecto, pues realmente eso es lo que queríamos hacer (indicar el link con la ruta del archivo en una carpeta del servidor) y lo que estábamos equivocados es en la denominación del tipo de campo a emplear, pues pensaba erróneamente que se denominaba DATOS ADJUNTOS upppssss

Muchas gracias Juanjo por tu pronta respuesta y te tomaré la palabra seguramente ;)

Muchas gracias de nuevo por todo!
Un saludo,
Javier
