### ISSUE TITLE
Infraestructura ideal sobre la que "funcionar" con ACCESS

### ISSUE THREAD

**Issue by JavierPriv** [ACCESSoTOTAL/Dudas#13]
Buenos días,
estamos valorando abordar con ACCESS una solución en dos clientes y la duda que tenemos es al respecto de los entornos donde pueden correr.
Idealmente nuestra idea es que tanto la BBDD  Backend como el Frontend fuesen ambos en ACCESS... pero tampoco nos importaría si técnicamente se precisa que la BBDD sea p.e. MySQL o otras.

Nosotros no somos de infraestructuras pero de cara a plantearle a uno de los clientes una solución de infraestructura y que sea compatible con ACCESS hemos buscado y leído post diversos y las conclusiones que hemos sacado de las lecturas es que:
- en entornos LAN: OK
- en entornos WAN: KO
- en entornos WAN: vía Terminal Server / Escritorio Remoto: OK --> el 1º de los Clientes tiene esta infraestructura.
- en entornos vía DROPBOX, ONEDRIVE: KO --> habíamos pensado en esta opción sencilla para el 2º Cliente que no tiene ninguno de los anteriores entornos (pues es muy pequeño) y solo tiene PCs individuales con conexión a Internet pero por lo que vemos con DROPBOX, ONEDRIVE no funcionaría.

¿Son correctas nuestras conclusiones anteriores?
¿Qué recomendaríais utilizar o ponerle al 2º Cliente y que sea un entorno lo más sencillo y económico posible para él pero sobretodo para poder hacerle correr ACCESS en sus usuarios de PC?
¿Conocéis algún link de información que podamos leer para "ilustrarnos" al respecto?

Muchas gracias de nuevo.
Saludos,
Javier Herranz

**Comment by lunasoft2001** [comment]
Tus conclusiones son correctas, si bien existen más opciones como Azure.

Respecto a la más económica, depende de lo que entiendas por económico: si tienes tu propio servidor/PC dedicado no pagas a terceros, pero debes tener todo el día encendido el PC por lo que el gasto eléctrico aumenta. De modo que la pregunta correcta sería cual es el modelo más rentable para mi modo de trabajar? 

Si lo deseas podemos tener una reunión online y vemos juntos la necesidad del cliente.  Juanjo@luna-soft.es

**Comment by JavierPriv** [comment]
Muchas gracias Juanjo,
y efectivamente tu apreciación es muy correcta respecto al término "más económica"... ;)

Te tomo la palabra y te contacto a tu mail para vernos online.
Muchas gracias de nuevo y buen fin de semana.

Un abrazo,
Javier
