### ISSUE TITLE
Soy contador y quiero realizar la contabilización con el menor dato posible mediante plantillas me prodria orientar gracias

### ISSUE THREAD

**Issue by cecatel** [ACCESSoTOTAL/Dudas#6]
**Descripción del problema:**
Escribe de manera concisa cual es la duda

**Código:**
```
Escribe aquí el código (si procede)
```

**Captura de pantalla:**
Aquí puedes colocar las capturas de pantalla que ayuden a entender el problema

**Archivos:**
Si lo deseas, puedes subir tu archivo

**Comment by lunasoft2001** [comment]
puedes ponerme un ejemplo de lo que quieres?
¿Qué problema tienes concretamente?
